export const GET_POKEMONS = 'GET_POKEMONS';
export const CALL_SAGA = 'CALL_SAGA';
export const ADD_POKEMON_CART = 'ADD_POKEMON_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const DELETE_POKEMON_CART = 'DELETE_POKEMON_CART';